# Generated by Django 5.2.1 on 2025-11-28 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watchlist', 'Watchlist'), ('watching', 'Watching'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('not_interested', 'Not Interested')], default='watchlist', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='User rating (1–10)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.cartoon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cartoon')},
            },
        ),
    ]
