# Generated by Django 5.2.1 on 2025-11-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
