# Generated by Django 5.2.1 on 2025-11-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_alter_userrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
