# Generated by Django 5.2.1 on 2025-11-29 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_userrating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
